# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60


# Velocity Controllers ---------------------------------------
left_rear_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_rear_wheel_joint
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
right_rear_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_rear_wheel_joint
  pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
left_front_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_front_wheel_joint
  pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
right_front_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_front_wheel_joint
  pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}


# Position Controllers ---------------------------------------
left_steering_hinge_position_controller:
  joint: left_steering_hinge_joint
  type: position_controllers/JointPositionController
  pid: {p: 1.0, i: 0.0, d: 0.5}
right_steering_hinge_position_controller:
  joint: right_steering_hinge_joint
  type: position_controllers/JointPositionController
  pid: {p: 1.0, i: 0.0, d: 0.5}

gazebo_ros_control/pid_gains:
  left_rear_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_wheel_joint: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_front_wheel_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_wheel_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_steering_hinge_joint: {p: 1.0, i: 0.0, d: 0.5}
  right_steering_hinge_joint: {p: 1.0, i: 0.0, d: 0.5}

