(cl:in-package deepracer_msgs-srv)
(cl:export '(LINK_NAME-VAL
          LINK_NAME
          VISUAL_NAME-VAL
          VISUAL_NAME
          AMBIENT-VAL
          AMBIENT
          DIFFUSE-VAL
          DIFFUSE
          SPECULAR-VAL
          SPECULAR
          EMISSIVE-VAL
          EMISSIVE
          TRANSPARENCY-VAL
          TRANSPARENCY
          VISIBLE-VAL
          VISIBLE
          GEOMETRY_TYPE-VAL
          GEOMETRY_TYPE
          MESH_GEOM_FILENAME-VAL
          MESH_GEOM_FILENAME
          MESH_GEOM_SCALE-VAL
          MESH_GEOM_SCALE
          POSE-VAL
          POSE
          SUCCESS-VAL
          SUCCESS
          STATUS_MESSAGE-VAL
          STATUS_MESSAGE
))