// Generated by gencpp from file deepracer_msgs/GetLinkStatesRequest.msg
// DO NOT EDIT!


#ifndef DEEPRACER_MSGS_MESSAGE_GETLINKSTATESREQUEST_H
#define DEEPRACER_MSGS_MESSAGE_GETLINKSTATESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepracer_msgs
{
template <class ContainerAllocator>
struct GetLinkStatesRequest_
{
  typedef GetLinkStatesRequest_<ContainerAllocator> Type;

  GetLinkStatesRequest_()
    : link_names()
    , reference_frames()  {
    }
  GetLinkStatesRequest_(const ContainerAllocator& _alloc)
    : link_names(_alloc)
    , reference_frames(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _link_names_type;
  _link_names_type link_names;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _reference_frames_type;
  _reference_frames_type reference_frames;





  typedef boost::shared_ptr< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLinkStatesRequest_

typedef ::deepracer_msgs::GetLinkStatesRequest_<std::allocator<void> > GetLinkStatesRequest;

typedef boost::shared_ptr< ::deepracer_msgs::GetLinkStatesRequest > GetLinkStatesRequestPtr;
typedef boost::shared_ptr< ::deepracer_msgs::GetLinkStatesRequest const> GetLinkStatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator1> & lhs, const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.link_names == rhs.link_names &&
    lhs.reference_frames == rhs.reference_frames;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator1> & lhs, const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepracer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "284df52820947bf6fdad4d9fe2eb3466";
  }

  static const char* value(const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x284df52820947bf6ULL;
  static const uint64_t static_value2 = 0xfdad4d9fe2eb3466ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepracer_msgs/GetLinkStatesRequest";
  }

  static const char* value(const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] link_names          # name of link\n"
"                             # link names are prefixed by model name, e.g. pr2::base_link\n"
"string[] reference_frames    # reference frame of returned information, must be a valid link\n"
"                             # if empty, use inertial (gazebo world) frame\n"
"                             # reference_frame names are prefixed by model name, e.g. pr2::base_link\n"
;
  }

  static const char* value(const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_names);
      stream.next(m.reference_frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLinkStatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepracer_msgs::GetLinkStatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_names[]" << std::endl;
    for (size_t i = 0; i < v.link_names.size(); ++i)
    {
      s << indent << "  link_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_names[i]);
    }
    s << indent << "reference_frames[]" << std::endl;
    for (size_t i = 0; i < v.reference_frames.size(); ++i)
    {
      s << indent << "  reference_frames[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reference_frames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPRACER_MSGS_MESSAGE_GETLINKSTATESREQUEST_H
