// Generated by gencpp from file deepracer_msgs/SetModelStates.msg
// DO NOT EDIT!


#ifndef DEEPRACER_MSGS_MESSAGE_SETMODELSTATES_H
#define DEEPRACER_MSGS_MESSAGE_SETMODELSTATES_H

#include <ros/service_traits.h>


#include <deepracer_msgs/SetModelStatesRequest.h>
#include <deepracer_msgs/SetModelStatesResponse.h>


namespace deepracer_msgs
{

struct SetModelStates
{

typedef SetModelStatesRequest Request;
typedef SetModelStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModelStates
} // namespace deepracer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepracer_msgs::SetModelStates > {
  static const char* value()
  {
    return "302646b3654009f39a95e719d97c8571";
  }

  static const char* value(const ::deepracer_msgs::SetModelStates&) { return value(); }
};

template<>
struct DataType< ::deepracer_msgs::SetModelStates > {
  static const char* value()
  {
    return "deepracer_msgs/SetModelStates";
  }

  static const char* value(const ::deepracer_msgs::SetModelStates&) { return value(); }
};


// service_traits::MD5Sum< ::deepracer_msgs::SetModelStatesRequest> should match 
// service_traits::MD5Sum< ::deepracer_msgs::SetModelStates > 
template<>
struct MD5Sum< ::deepracer_msgs::SetModelStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_msgs::SetModelStates >::value();
  }
  static const char* value(const ::deepracer_msgs::SetModelStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_msgs::SetModelStatesRequest> should match 
// service_traits::DataType< ::deepracer_msgs::SetModelStates > 
template<>
struct DataType< ::deepracer_msgs::SetModelStatesRequest>
{
  static const char* value()
  {
    return DataType< ::deepracer_msgs::SetModelStates >::value();
  }
  static const char* value(const ::deepracer_msgs::SetModelStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepracer_msgs::SetModelStatesResponse> should match 
// service_traits::MD5Sum< ::deepracer_msgs::SetModelStates > 
template<>
struct MD5Sum< ::deepracer_msgs::SetModelStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_msgs::SetModelStates >::value();
  }
  static const char* value(const ::deepracer_msgs::SetModelStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_msgs::SetModelStatesResponse> should match 
// service_traits::DataType< ::deepracer_msgs::SetModelStates > 
template<>
struct DataType< ::deepracer_msgs::SetModelStatesResponse>
{
  static const char* value()
  {
    return DataType< ::deepracer_msgs::SetModelStates >::value();
  }
  static const char* value(const ::deepracer_msgs::SetModelStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPRACER_MSGS_MESSAGE_SETMODELSTATES_H
