// Generated by gencpp from file deepracer_msgs/SetVisualTransparencyRequest.msg
// DO NOT EDIT!


#ifndef DEEPRACER_MSGS_MESSAGE_SETVISUALTRANSPARENCYREQUEST_H
#define DEEPRACER_MSGS_MESSAGE_SETVISUALTRANSPARENCYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepracer_msgs
{
template <class ContainerAllocator>
struct SetVisualTransparencyRequest_
{
  typedef SetVisualTransparencyRequest_<ContainerAllocator> Type;

  SetVisualTransparencyRequest_()
    : link_name()
    , visual_name()
    , transparency(0.0)
    , block(false)  {
    }
  SetVisualTransparencyRequest_(const ContainerAllocator& _alloc)
    : link_name(_alloc)
    , visual_name(_alloc)
    , transparency(0.0)
    , block(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _link_name_type;
  _link_name_type link_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _visual_name_type;
  _visual_name_type visual_name;

   typedef double _transparency_type;
  _transparency_type transparency;

   typedef uint8_t _block_type;
  _block_type block;





  typedef boost::shared_ptr< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVisualTransparencyRequest_

typedef ::deepracer_msgs::SetVisualTransparencyRequest_<std::allocator<void> > SetVisualTransparencyRequest;

typedef boost::shared_ptr< ::deepracer_msgs::SetVisualTransparencyRequest > SetVisualTransparencyRequestPtr;
typedef boost::shared_ptr< ::deepracer_msgs::SetVisualTransparencyRequest const> SetVisualTransparencyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator1> & lhs, const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.link_name == rhs.link_name &&
    lhs.visual_name == rhs.visual_name &&
    lhs.transparency == rhs.transparency &&
    lhs.block == rhs.block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator1> & lhs, const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepracer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0d82fd0dbd853e003e00b15ba8396e5";
  }

  static const char* value(const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0d82fd0dbd853e0ULL;
  static const uint64_t static_value2 = 0x03e00b15ba8396e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepracer_msgs/SetVisualTransparencyRequest";
  }

  static const char* value(const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string link_name\n"
"string visual_name\n"
"float64 transparency\n"
"bool block\n"
;
  }

  static const char* value(const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_name);
      stream.next(m.visual_name);
      stream.next(m.transparency);
      stream.next(m.block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVisualTransparencyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepracer_msgs::SetVisualTransparencyRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.link_name);
    s << indent << "visual_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.visual_name);
    s << indent << "transparency: ";
    Printer<double>::stream(s, indent + "  ", v.transparency);
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPRACER_MSGS_MESSAGE_SETVISUALTRANSPARENCYREQUEST_H
