// Generated by gencpp from file deepracer_msgs/SetVisualColors.msg
// DO NOT EDIT!


#ifndef DEEPRACER_MSGS_MESSAGE_SETVISUALCOLORS_H
#define DEEPRACER_MSGS_MESSAGE_SETVISUALCOLORS_H

#include <ros/service_traits.h>


#include <deepracer_msgs/SetVisualColorsRequest.h>
#include <deepracer_msgs/SetVisualColorsResponse.h>


namespace deepracer_msgs
{

struct SetVisualColors
{

typedef SetVisualColorsRequest Request;
typedef SetVisualColorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVisualColors
} // namespace deepracer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepracer_msgs::SetVisualColors > {
  static const char* value()
  {
    return "2b593b9606746213e8e7b797a0ade086";
  }

  static const char* value(const ::deepracer_msgs::SetVisualColors&) { return value(); }
};

template<>
struct DataType< ::deepracer_msgs::SetVisualColors > {
  static const char* value()
  {
    return "deepracer_msgs/SetVisualColors";
  }

  static const char* value(const ::deepracer_msgs::SetVisualColors&) { return value(); }
};


// service_traits::MD5Sum< ::deepracer_msgs::SetVisualColorsRequest> should match 
// service_traits::MD5Sum< ::deepracer_msgs::SetVisualColors > 
template<>
struct MD5Sum< ::deepracer_msgs::SetVisualColorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_msgs::SetVisualColors >::value();
  }
  static const char* value(const ::deepracer_msgs::SetVisualColorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_msgs::SetVisualColorsRequest> should match 
// service_traits::DataType< ::deepracer_msgs::SetVisualColors > 
template<>
struct DataType< ::deepracer_msgs::SetVisualColorsRequest>
{
  static const char* value()
  {
    return DataType< ::deepracer_msgs::SetVisualColors >::value();
  }
  static const char* value(const ::deepracer_msgs::SetVisualColorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepracer_msgs::SetVisualColorsResponse> should match 
// service_traits::MD5Sum< ::deepracer_msgs::SetVisualColors > 
template<>
struct MD5Sum< ::deepracer_msgs::SetVisualColorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_msgs::SetVisualColors >::value();
  }
  static const char* value(const ::deepracer_msgs::SetVisualColorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_msgs::SetVisualColorsResponse> should match 
// service_traits::DataType< ::deepracer_msgs::SetVisualColors > 
template<>
struct DataType< ::deepracer_msgs::SetVisualColorsResponse>
{
  static const char* value()
  {
    return DataType< ::deepracer_msgs::SetVisualColors >::value();
  }
  static const char* value(const ::deepracer_msgs::SetVisualColorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPRACER_MSGS_MESSAGE_SETVISUALCOLORS_H
