ARG CORE_PREFIX=awsdeepracercommunity
ARG CORE_TAG=latest
FROM $CORE_PREFIX/deepracer-simapp-build-core:${CORE_TAG}

COPY bundle/ /opt/amazon
COPY docker/files/ml-code/ /opt/ml/code
WORKDIR /opt/amazon

RUN bash -c "/opt/ml/code/scripts/build_deepracer_ros_packages_lite.sh"

ENTRYPOINT ["/bin/bash", "-c"]