# This is a sample file that shows how one can easily build docker images
# inheriting one of the core images. It will copy in the bundle and the run.sh
# but otherwise not install packages etc. again.
#
# Build with 'docker build . -t awsdeepracercommunity/deepracer-robomaker:local -f docker/Dockerfile.localext --build-arg FROM_TAG=cpu-avx'
#
ARG FROM_TAG
FROM awsdeepracercommunity/deepracer-robomaker:${FROM_TAG}

RUN apt-get update && apt-get install -y ros-melodic-imu-tools
COPY bundle/deepracer_simulation_environment/share/deepracer_simulation_environment/urdf /opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/urdf
#COPY ./docker/files/run.sh run.sh

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["./run.sh run distributed_training.launch"]
