ARG CORE_PREFIX=awsdeepracercommunity
FROM $CORE_PREFIX/deepracer-env-build-core:latest

COPY simulation/ /opt/bundle
COPY deepracer_env/ /opt/bundle/deepracer_env/
WORKDIR /opt/bundle

RUN rosdep update --rosdistro=noetic -q && rosdep install --rosdistro=noetic --from-paths src --ignore-src -r -y 
RUN bash -c "source /opt/ros/noetic/setup.bash && colcon build"

ENTRYPOINT ["/simulation-entrypoint.sh"]
CMD ["bash"]