ARG CORE_PREFIX=awsdeepracercommunity
FROM $CORE_PREFIX/deepracer-robomaker-build-core:latest

COPY bundle/ /opt/bundle
WORKDIR /opt/bundle

RUN rosdep update --include-eol-distros && rosdep install --from-paths src --ignore-src -r -y 
RUN bash -c "source /opt/ros/noetic/setup.bash && colcon build"

ENTRYPOINT ["/simulation-entrypoint.sh"]
CMD ["bash"]