ARG FROM_IMG=awsdeepracercommunity/deepracer-robomaker-build-core:latest
FROM ${FROM_IMG}

ARG USERNAME=user-name-goes-here
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]