version: "3.7"

networks:
  default:
    external: true
    name: sagemaker-local

services:
  robomaker:
    build:
      context: .
      dockerfile: Dockerfile.localuser
      args:
        FROM_IMG: awsdeepracercommunity/deepracer-simapp:${DR_ROBOMAKER_IMAGE}
        USERNAME: $USER
        USER_UID: $USER_UID
        USER_GID: $USER_GID
    entrypoint: [ "/bin/bash", "-c" ]
    command: [ "/opt/files/devel.sh" ]
    ports:
      - "5900:5900"
    environment:
      - DISPLAY
      - DR_WORLD_NAME
      - XAUTHORITY=$HOME/.Xauthority
      - QT_X11_NO_MITSHM=1
      - CUDA_VISIBLE_DEVICES
      - XDG_RUNTIME_DIR=/tmp/runtime-$USER
    volumes:
      - '../docker/files:/opt/files'
      - '../install:/opt/install'
      - '/tmp/.X11-unix/:/tmp/.X11-unix'
      - '${XAUTHORITY}:$HOME/.Xauthority'
