ARG CORE_PREFIX=awsdeepracercommunity
FROM $CORE_PREFIX/deepracer-simapp-build-core:latest

COPY bundle/ /opt/amazon
COPY docker/files/ml-code/ /opt/ml/code
WORKDIR /opt/amazon

RUN bash -c "/opt/ml/code/scripts/build_deepracer_ros_packages_lite.sh"

ENTRYPOINT ["/simulation-entrypoint.sh"]
CMD ["bash"]