# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from deepracer_simulation_environment/VideoMetricsSrvRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VideoMetricsSrvRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "deepracer_simulation_environment/VideoMetricsSrvRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VideoMetricsSrvRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from deepracer_simulation_environment/VideoMetricsSrvResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VideoMetricsSrvResponse(genpy.Message):
  _md5sum = "da26613e841a5a2b4eb38f31404241d7"
  _type = "deepracer_simulation_environment/VideoMetricsSrvResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 lap_counter
float32 completion_percentage
int32 reset_counter
float32 throttle
float32 steering
float32 best_lap_time
float32 total_evaluation_time
bool done
"""
  __slots__ = ['lap_counter','completion_percentage','reset_counter','throttle','steering','best_lap_time','total_evaluation_time','done']
  _slot_types = ['float32','float32','int32','float32','float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lap_counter,completion_percentage,reset_counter,throttle,steering,best_lap_time,total_evaluation_time,done

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VideoMetricsSrvResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lap_counter is None:
        self.lap_counter = 0.
      if self.completion_percentage is None:
        self.completion_percentage = 0.
      if self.reset_counter is None:
        self.reset_counter = 0
      if self.throttle is None:
        self.throttle = 0.
      if self.steering is None:
        self.steering = 0.
      if self.best_lap_time is None:
        self.best_lap_time = 0.
      if self.total_evaluation_time is None:
        self.total_evaluation_time = 0.
      if self.done is None:
        self.done = False
    else:
      self.lap_counter = 0.
      self.completion_percentage = 0.
      self.reset_counter = 0
      self.throttle = 0.
      self.steering = 0.
      self.best_lap_time = 0.
      self.total_evaluation_time = 0.
      self.done = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2fi4fB().pack(_x.lap_counter, _x.completion_percentage, _x.reset_counter, _x.throttle, _x.steering, _x.best_lap_time, _x.total_evaluation_time, _x.done))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.lap_counter, _x.completion_percentage, _x.reset_counter, _x.throttle, _x.steering, _x.best_lap_time, _x.total_evaluation_time, _x.done,) = _get_struct_2fi4fB().unpack(str[start:end])
      self.done = bool(self.done)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2fi4fB().pack(_x.lap_counter, _x.completion_percentage, _x.reset_counter, _x.throttle, _x.steering, _x.best_lap_time, _x.total_evaluation_time, _x.done))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.lap_counter, _x.completion_percentage, _x.reset_counter, _x.throttle, _x.steering, _x.best_lap_time, _x.total_evaluation_time, _x.done,) = _get_struct_2fi4fB().unpack(str[start:end])
      self.done = bool(self.done)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fi4fB = None
def _get_struct_2fi4fB():
    global _struct_2fi4fB
    if _struct_2fi4fB is None:
        _struct_2fi4fB = struct.Struct("<2fi4fB")
    return _struct_2fi4fB
class VideoMetricsSrv(object):
  _type          = 'deepracer_simulation_environment/VideoMetricsSrv'
  _md5sum = 'da26613e841a5a2b4eb38f31404241d7'
  _request_class  = VideoMetricsSrvRequest
  _response_class = VideoMetricsSrvResponse
