// Generated by gencpp from file deepracer_simulation_environment/VideoMetricsSrv.msg
// DO NOT EDIT!


#ifndef DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIDEOMETRICSSRV_H
#define DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIDEOMETRICSSRV_H

#include <ros/service_traits.h>


#include <deepracer_simulation_environment/VideoMetricsSrvRequest.h>
#include <deepracer_simulation_environment/VideoMetricsSrvResponse.h>


namespace deepracer_simulation_environment
{

struct VideoMetricsSrv
{

typedef VideoMetricsSrvRequest Request;
typedef VideoMetricsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VideoMetricsSrv
} // namespace deepracer_simulation_environment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrv > {
  static const char* value()
  {
    return "da26613e841a5a2b4eb38f31404241d7";
  }

  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrv&) { return value(); }
};

template<>
struct DataType< ::deepracer_simulation_environment::VideoMetricsSrv > {
  static const char* value()
  {
    return "deepracer_simulation_environment/VideoMetricsSrv";
  }

  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrvRequest> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::VideoMetricsSrvRequest> should match 
// service_traits::DataType< ::deepracer_simulation_environment::VideoMetricsSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::VideoMetricsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::VideoMetricsSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrvResponse> should match 
// service_traits::MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrv > 
template<>
struct MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepracer_simulation_environment::VideoMetricsSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepracer_simulation_environment::VideoMetricsSrvResponse> should match 
// service_traits::DataType< ::deepracer_simulation_environment::VideoMetricsSrv > 
template<>
struct DataType< ::deepracer_simulation_environment::VideoMetricsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::deepracer_simulation_environment::VideoMetricsSrv >::value();
  }
  static const char* value(const ::deepracer_simulation_environment::VideoMetricsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIDEOMETRICSSRV_H
