// Generated by gencpp from file deepracer_simulation_environment/VirtualEventVideoEditSrvResponse.msg
// DO NOT EDIT!


#ifndef DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIRTUALEVENTVIDEOEDITSRVRESPONSE_H
#define DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIRTUALEVENTVIDEOEDITSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepracer_simulation_environment
{
template <class ContainerAllocator>
struct VirtualEventVideoEditSrvResponse_
{
  typedef VirtualEventVideoEditSrvResponse_<ContainerAllocator> Type;

  VirtualEventVideoEditSrvResponse_()
    : success(false)  {
    }
  VirtualEventVideoEditSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualEventVideoEditSrvResponse_

typedef ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<std::allocator<void> > VirtualEventVideoEditSrvResponse;

typedef boost::shared_ptr< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse > VirtualEventVideoEditSrvResponsePtr;
typedef boost::shared_ptr< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse const> VirtualEventVideoEditSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator1> & lhs, const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator1> & lhs, const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deepracer_simulation_environment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepracer_simulation_environment/VirtualEventVideoEditSrvResponse";
  }

  static const char* value(const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualEventVideoEditSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepracer_simulation_environment::VirtualEventVideoEditSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPRACER_SIMULATION_ENVIRONMENT_MESSAGE_VIRTUALEVENTVIDEOEDITSRVRESPONSE_H
