#!/bin/bash

if [[ -f "$HOME/.bashrc" ]]; then
    source $HOME/.bashrc
fi

# Detect Architecture
echo "System Architecture: $(dpkg --print-architecture)"

# Detect ROS version
if [ -f /opt/ros/noetic/setup.bash ]; then
    ROS_DISTRO="noetic"
elif [ -f /opt/ros/humble/setup.bash ]; then
    ROS_DISTRO="humble"
elif [ -f /opt/ros/jazzy/setup.bash ]; then
    ROS_DISTRO="jazzy"
else
    echo "Unsupported ROS version"
    exit 1
fi
echo "Detected ROS version: $ROS_DISTRO"
source /opt/ros/$ROS_DISTRO/setup.bash
