// Generated by gencpp from file robomaker_simulation_msgs/Cancel.msg
// DO NOT EDIT!


#ifndef ROBOMAKER_SIMULATION_MSGS_MESSAGE_CANCEL_H
#define ROBOMAKER_SIMULATION_MSGS_MESSAGE_CANCEL_H

#include <ros/service_traits.h>


#include <robomaker_simulation_msgs/CancelRequest.h>
#include <robomaker_simulation_msgs/CancelResponse.h>


namespace robomaker_simulation_msgs
{

struct Cancel
{

typedef CancelRequest Request;
typedef CancelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Cancel
} // namespace robomaker_simulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robomaker_simulation_msgs::Cancel > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::robomaker_simulation_msgs::Cancel&) { return value(); }
};

template<>
struct DataType< ::robomaker_simulation_msgs::Cancel > {
  static const char* value()
  {
    return "robomaker_simulation_msgs/Cancel";
  }

  static const char* value(const ::robomaker_simulation_msgs::Cancel&) { return value(); }
};


// service_traits::MD5Sum< ::robomaker_simulation_msgs::CancelRequest> should match 
// service_traits::MD5Sum< ::robomaker_simulation_msgs::Cancel > 
template<>
struct MD5Sum< ::robomaker_simulation_msgs::CancelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robomaker_simulation_msgs::Cancel >::value();
  }
  static const char* value(const ::robomaker_simulation_msgs::CancelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robomaker_simulation_msgs::CancelRequest> should match 
// service_traits::DataType< ::robomaker_simulation_msgs::Cancel > 
template<>
struct DataType< ::robomaker_simulation_msgs::CancelRequest>
{
  static const char* value()
  {
    return DataType< ::robomaker_simulation_msgs::Cancel >::value();
  }
  static const char* value(const ::robomaker_simulation_msgs::CancelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robomaker_simulation_msgs::CancelResponse> should match 
// service_traits::MD5Sum< ::robomaker_simulation_msgs::Cancel > 
template<>
struct MD5Sum< ::robomaker_simulation_msgs::CancelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robomaker_simulation_msgs::Cancel >::value();
  }
  static const char* value(const ::robomaker_simulation_msgs::CancelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robomaker_simulation_msgs::CancelResponse> should match 
// service_traits::DataType< ::robomaker_simulation_msgs::Cancel > 
template<>
struct DataType< ::robomaker_simulation_msgs::CancelResponse>
{
  static const char* value()
  {
    return DataType< ::robomaker_simulation_msgs::Cancel >::value();
  }
  static const char* value(const ::robomaker_simulation_msgs::CancelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOMAKER_SIMULATION_MSGS_MESSAGE_CANCEL_H
