(cl:defpackage robomaker_simulation_msgs-srv
  (:use )
  (:export
   "ADDTAGS"
   "<ADDTAGS-REQUEST>"
   "ADDTAGS-REQUEST"
   "<ADDTAGS-RESPONSE>"
   "ADDTAGS-RESPONSE"
   "CANCEL"
   "<CANCEL-REQUEST>"
   "CANCEL-REQUEST"
   "<CANCEL-RESPONSE>"
   "CANCEL-RESPONSE"
   "LISTTAGS"
   "<LISTTAGS-REQUEST>"
   "LISTTAGS-REQUEST"
   "<LISTTAGS-RESPONSE>"
   "LISTTAGS-RESPONSE"
   "REMOVETAGS"
   "<REMOVETAGS-REQUEST>"
   "REMOVETAGS-REQUEST"
   "<REMOVETAGS-RESPONSE>"
   "REMOVETAGS-RESPONSE"
  ))

