string[] link_names          # name of link
                             # link names are prefixed by model name, e.g. pr2::base_link
string[] reference_frames    # reference frame of returned information, must be a valid link
                             # if empty, use inertial (gazebo world) frame
                             # reference_frame names are prefixed by model name, e.g. pr2::base_link
---
gazebo_msgs/LinkState[] link_states
bool success                 # return true if get info is successful
string status_message        # comments if available
int8[] status                # status of each request: true if succeeded otherwise false
string[] messages